version: '3.8'

services:
  # 1. BAZA DANYCH
  postgres:
    image: postgres:15-alpine
    container_name: rg-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ReportGeneratorDb
    ports:
      - "5432:5432"

  # 2. MESSAGE BROKER
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rg-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # 3. SERWER PLIKÓW
  minio:
    image: minio/minio
    container_name: rg-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  seq:
    image: datalust/seq:latest
    container_name: rg-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Admin123!
    ports:
      - "5341:5341"
      - "8081:80"